spring.application.name=saude
# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/fila_ubs_db?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Redis - instala o Redis depois: https://redis.io/docs/getting-started/
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Libera CORS pro seu React
spring.web.cors.allowed-origins=http://localhost:5173

spring.sql.init.mode=always
# Configuração do Banco de Dados MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configurações do Hibernate / JPA
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Desativar o aviso chato do Open-In-View que apareceu no seu log
spring.jpa.open-in-view=false